spring:
  application:
    name: config-server

server:
  port: 8888

eureka:
  client:
    service-url:
      # Point to the Eureka Server so this service can register itself there
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
